In [1]:
import tensorflow.compat.v1 as tf #Low level tensorflow

In [2]:
tf.disable_eager_execution()  # we want all executions in low level form

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
import numpy as np

In [19]:
#Making variables in tensorflow

v1 = tf.Variable(57, name = 'v1')   #Note, we're assigning a name when declaring it because the name of this declared variable,
v2 = tf.Variable(63, name = 'v2')   #needs to be reflected on the tensorboard. 
v3 = tf.Variable(1, name = 'v3')
v4 = tf.Variable(5, name = 'v4')

z = pow(v1, 4) + pow(v2, 2) + v1 * v3 * v4

#Declaring constant &broadcasting in tensorflow

a1 = tf.constant(3)
a2 = a1 + 15
a3 = a2 * 4


#Matrix Operations with tf

#Multiplication.

p = tf.ones((8,4))    #2-D tensor of ones(1's) having shape of 8 rows and 4 columns
q = tf.zeros((4 , 8))
r = tf.ones((8, 8))  

y = tf.matmul(p, q) + r

#So we want to multiply two matrices p and q, and add the result to r, in order to multiply two matrix , the column of the first
#as to be equal to the number of row of the second matrix.. above, p has 4 columns and q has 4 rows, which implies that they can
#be multiplied.

#Matrix Determinant, Inverse, Diagonal, Transpose

arr = np.array([[6.8,7.5,8.0], [8.1,9.2,0.5], [5.1,5.2,4.3]]) # a 4 X 3 array

max_dtr = tf.matrix_determinant(arr) 

max_inverse = tf.matrix_inverse(arr)

max_diag = tf.matrix_diag(max_inverse)

max_trans = tf.matrix_transpose(max_inverse)

#Argmax, Argmin

arg_1 = np.array([5.8, 9.0])

max_1 = tf.argmax(arg_1, name = 'max_1')
min_1 = tf.argmin(arg_1, name = 'min_1')

#Confusion Matrix, Random_Uniform, Round

rand_1 = tf.random_uniform((10,), minval = 0, maxval = 1) #generates 10 random floats between 0 and 1
rand_2 = tf.random_uniform((10,), minval = 0, maxval = 1)

y_pred = tf.round(rand_1, 'y_pred') #it rounds off all the floats generated to the nearest integer
y_true = tf.round(rand_2, 'y_true')

conf_mat = tf.confusion_matrix(y_pred, y_true, name = 'confusion_matrix')

#Placeholders

A1 = tf.placeholder(tf.float32, shape = (None, 4)) #Placeholder are like inputs to dummy containers, the hold information to
B1 = A1 + 2                                        #be processed


#SO WE WILL RUN ALL THE ABOVE TENSORS IN SESSIONS.. It is a means of executing tensorflow graphs

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    
    result_1 = z.eval()
    print('basic operations with tensorflow variables')
    print(result_1)
    
    result_2 = a3.eval()
    print('basic operations with tensorflow variables')
    print(result_2)
    
    result_3 = y.eval()
    print('Matrix operations with tensorflow')
    print(result_3)
    
    result_4 = max_dtr.eval()
    result_5 = max_inverse.eval()
    result_6 = max_diag.eval()
    result_7 = max_trans.eval()
    
    print('Matrix operations with tensorflow')
    print(result_4, result_5, result_6, result_7)
    
    print('index of maximum of a few numbers')
    print(max_1.eval())

    print('index of minimum of a few numbers')
    print(min_1.eval())

    print('Confusion matrix')
    print(conf_mat.eval())

    b_val = B1.eval(feed_dict={A1:[[1,2,3, 4]]})
    b_val_u = B1.eval(feed_dict= {A1:[[4,5,6,8],[7,8,9, 10]]})
    print('Placeholders')
    print(b_val)
    print(b_val_u)









basic operations with tensorflow variables
10560255
basic operations with tensorflow variables
72
Matrix operations with tensorflow
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
Matrix operations with tensorflow
-29.17199999999999 [[-1.26696833 -0.32051282  2.39441931]
 [ 1.10654052  0.3962704  -2.10475799]
 [ 0.16454134 -0.0990676  -0.0620458 ]] [[[-1.26696833  0.          0.        ]
  [ 0.         -0.32051282  0.        ]
  [ 0.          0.          2.39441931]]

 [[ 1.10654052  0.          0.        ]
  [ 0.          0.3962704   0.        ]
  [ 0.          0.         -2.10475799]]

 [[ 0.16454134  0.          0.        ]
  [ 0.         -0.0990676   0.        ]
  [ 0.          0.         -0.0620458 ]]] [[-1.26696833  1.10654052  0.16454134]
 [-0.32051282  0.3962704  -0.0990676 ]
 [ 2.39441931 -2.10475799 -0.0620458

(2, 3)